### ISSUE TITLE
dotnet-buildpack fails on dokku

### ISSUE THREAD

**Issue by sampettersson** [progrium/buildstep#147]
I am trying to push a yeoman generated Asp.net 5 webapplication using the heroku dotnet buildpack on dokku, after several tries it always ends with "ERROR building certificate chain:[...]".

Here's the full stacktrace of a push: https://gist.github.com/sampettersson/cde3199b4166182d773b

The buildpack in use: https://github.com/heroku/dotnet-buildpack

Considering this works on heroku i suppose this is a buildstep issue?

**Comment by progrium** [comment]
Can you try this? https://github.com/gliderlabs/herokuish#using-herokuish-to-test-herokudokku-apps

That output will let us know if it's a buildpack issue or something else. It's also a lot easier to look through.

**Comment by sampettersson** [comment]
Here's the output of that: https://gist.github.com/sampettersson/52a2b47366d915062ffc
It's seems to be something going on with mono during a ´kpm restore´.

**Comment by progrium** [comment]
Yeah, I don't really know what's going on or how to debug that. You should
share that with the buildpack author to see if they have ideas.

On Sat, Apr 4, 2015 at 8:18 PM, Sam Pettersson <notifications@github.com>
wrote:

> Here's the output of that:
> https://gist.github.com/sampettersson/52a2b47366d915062ffc
> It's seems to be something going on with mono during a ´kpm restore´.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/buildstep/issues/147#issuecomment-89697538>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by sampettersson** [comment]
I did some digging, concluded that the errors are because of https://www.nuget.org not getting it's certificates trusted, this is supposed to be fixed by ´mozroots --import --sync --quiet´ and it does so on heroku but not in buildstep. Running nuget with http instead works for now.

And another thing i found is that buildstep isn't exposing the port that is to be used, this creates an issue when the buildpack creates it's own procfile making ´klr´ not knowing which port it should bind.
https://github.com/heroku/dotnet-buildpack/blob/master/bin/compile (line 119)

I don't know how to get any further on this, isn't the port supposed to be available while running ´compile´? Do you have any ideas on how to go around this?

Thanks!

**Comment by progrium** [comment]
In line 119 it's writing to a file that's executed during start, which by
convention has PORT set, so that's fine. The \ before $PORT escapes it. So
that should be an issue. What makes you think it is?

With mozroots, as far as I know Heroku is not doing this in their base
image (we use the same script to build out base images). I wonder why the
buildpack itself doesn't do this.

On Sun, Apr 5, 2015 at 6:05 AM, Sam Pettersson <notifications@github.com>
wrote:

> I did some digging, concluded that the errors are because of
> https://www.nuget.org not getting it's certificates trusted, this is
> supposed to be fixed by ´mozroots --import --sync --quiet´ and it does so
> on heroku but not in buildstep. Running nuget with http instead works for
> now.
>
> And another thing i found is that buildstep isn't exposing the port that
> is to be used, this creates an issue when the buildpack creates it's own
> procfile making ´klr´ not knowing which port it should bind.
> https://github.com/heroku/dotnet-buildpack/blob/master/bin/compile (line
> 119)
>
> I don't know how to get any further on this, isn't the port supposed to be
> available while running ´compile´? Do you have any ideas on how to go
> around this?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/buildstep/issues/147#issuecomment-89753533>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by sampettersson** [comment]
Yeah, i noticed that after I wrote the comment. Everything seems to be running as it should now, except for the https issue.

In the buildpack itself the ´mozroots --import --sync --quiet´ is invoked which handles certificates on heroku (i suppose), but in buildstep this doesn't do the trick. Could altogether be caused by something else but after looking into it the exceptions should be fixed by running ´mozroots´ and/or ´certmgr´ (which doesn't work because of permission issues).

**Comment by progrium** [comment]
So you're saying it *should* be fixed by calling `mozroots`, and it *does* call it but it doesn't work. Which doesn't work because of permission issues? Both?

**Comment by sampettersson** [comment]
Sorry for the confusions, `mozroots` is called in the buildpack but doesn't solve the issues, `certmgr` however doesn't work as it should due to permission issues while adding the certificates to store, `certmgr` is not called in the buildpack.

**Comment by progrium** [comment]
Can you point to reference material on this? I'm trying to figure out why that would solve the issue despite it seemingly not being called on Heroku.

**Comment by sampettersson** [comment]
Basically this is what i found so far:
https://github.com/aspnet/Home/issues/197
https://github.com/aspnet/Home/issues/89
https://itofinity.wordpress.com/2014/06/04/hello-new-k-world-kpm-restore-fail-part-1/
http://weblogs.thinktecture.com/cweyer/2014/10/installing-running-aspnet-vnext-alpha-3-on-ubuntu-linux-with-mono-38for-real.html

Afaik certmgr should be run to import the needed certificates, as why it's not needed on heroku i don't know.

**Comment by progrium** [comment]
You should be able to test this hypothesis using Herokuish. 
```
$ docker run --name certmgr gliderlabs/herokuish bash -c "apt-get update && apt-get install -y certmgr" # or whatever
$ docker commit certmgr gliderlabs/herokuish:certmgr
```
Then do the original test for your app using your custom `:certmgr` tag of herokuish.
